import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Main Page",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <>      
    {children}
    </>
  );
}
